FROM python:3.10-slim

WORKDIR /app

# install system deps for OpenCV + multipart
RUN apt-get update && apt-get install -y \
    git curl libgl1 libglib2.0-0 \
 && rm -rf /var/lib/apt/lists/*

# python packages
RUN pip install --no-cache-dir ultralytics fastapi uvicorn pillow python-multipart

COPY app/ /app/
COPY mlflow/mlartifacts/yolo-experiments/exp-mlflow/weights/best.pt /app/weights/best.pt

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
